# Generated by Django 4.1.2 on 2023-01-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('register_user', 'User can acces registration form and send invitaion to app')]},
        ),
    ]
