version: '3.8'

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    image: errander:latest
    env_file:
      - ./web/.env
    ports:
      - 8001:8005
    depends_on:
      - postgres_db
    entrypoint: bash ./web/scripts/development/entrypoint.sh
    volumes:
      - .:/web
  postgres_db:
    image: postgres:13-alpine
    env_file:
      - ./web/.env
    expose:
      - 5435
    ports:
      - 5435:5435
    command: -p 5435
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: