version: '3.8'

services:
  web:
    build: .
    image: errander:latest
    ports:
      - 8000:8000
    depends_on:
      - postgres
    entrypoint: bash entrypoint.sh
    volumes:
      - .:/app
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB_NAME}
    ports:
      - 5432:5432
    restart: always