# Generated by Django 4.1.5 on 2023-01-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0003_errand_address_errand_geolocation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errand',
            options={'permissions': [('create', 'User can create Errand object'), ('assign_users', 'User can add users to Errand object'), ('can_list_and_view_every_errand', 'User can view every existing errand')]},
        ),
    ]
