# Generated by Django 4.1.2 on 2023-01-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErranderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=64)),
                ('token_generated_timestamp', models.DateTimeField(auto_now_add=True)),
                ('account_activation_timestamp', models.DateTimeField(default=None)),
                ('reset_password_timestamp', models.DateTimeField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
