# Generated by Django 4.1.2 on 2023-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0002_alter_errand_options_alter_errand_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='address',
            field=models.CharField(max_length=200, null=False),
        ),
        migrations.AddField(
            model_name='errand',
            name='geolocation',
            field=models.CharField(max_length=200, null=False),
        ),
        migrations.AddField(
            model_name='historicalerrand',
            name='address',
            field=models.CharField(max_length=200, null=False),
        ),
        migrations.AddField(
            model_name='historicalerrand',
            name='geolocation',
            field=models.CharField(max_length=200, null=False),
        ),
    ]
