# Generated by Django 4.1.5 on 2023-02-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0005_alter_errand_options_alter_errand_assigned_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errand',
            options={'permissions': [('create', 'User can create Errand object'), ('assign_users', 'User can add/remove users to Errand object'), ('can_list_and_view_every_errand', 'User can view every existing errand'), ('access_history', 'User can access history of errand')]},
        ),
    ]
