name: Build Docker container & Push to DockerHub Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_app:
    uses: karol-bekieszczuk/errander/.github/workflows/test-app.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_app]
    env:
      SECRET_KEY: django-insecure-test-secret-key
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: web
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/errander:latest, ${{ secrets.DOCKERHUB_USERNAME }}/errander:${{ github.sha }}
          cache-from: |
      - name: Install and configure kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}
          kubectl-version: v1.27.1
      - name: Restart Deployment
        run: | 
          kubectl apply -f k8s/apps/errander.yaml
          kubectl set image deployment/errander-deployment errander=${{ secrets.DOCKERHUB_USERNAME }}/errander:${{ github.sha }}
          kubectl rollout restart deployment/errander-deployment
      - name: Wait for rollout restart to finish
        run: kubectl rollout status deployment/errander-deployment
      - name: Migrate database
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=errander-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /web/scripts/production/migrate.sh