name: Build Docker container & Push to DockerHub Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_app:
    uses: karol-bekieszczuk/errander/.github/workflows/test-app.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_app]
    env:
      SECRET_KEY: django-insecure-test-secret-key
    steps:
      - uses: actions/checkout@v3