name: Build Docker container & Push to DockerHub Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_app:
    uses: karol-bekieszczuk/errander/.github/workflows/test-app.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_app]
    env:
      SECRET_KEY: django-insecure-test-secret-key
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: web
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/errander:latest, ${{ secrets.DOCKERHUB_USERNAME }}/errander:${{ github.sha }}
          cache-from: |
      - name: Install and configure kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}
          kubectl-version: v1.27.1
      - name: Restart Deployment
        run: kubectl rollout restart deployment/errander-deployment