# Generated by Django 4.1.5 on 2023-01-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('register_user', 'User can acces registration form and send invitaion to app'), ('view_index', 'User can view index of all app users'), ('view_any_user', 'User can view any user in profile page')]},
        ),
    ]
